### ISSUE TITLE
[add] 초기 프로젝트 셋팅

### ISSUE THREAD

**Issue by i-colours-u** [teamTridy/Tridy_iOS#1]
## Task List
- [x] gitignore 추가
- [x] SwiftLint 파일 추가
- [x] fastLane 셋팅
- [x] Cocoapod 기타 세팅
- [x] info.plist 경로 수정
